import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = new URL('../', import.meta.url);
const bundle = await build({
  absWorkingDir: fileURLToPath(root),
  entryPoints: ['web/app.tsx'],
  bundle: true,
  platform: 'browser',
  format: 'esm',
  target: 'es2022',
  minify: true,
  define: { 'process.env.NODE_ENV': '"production"' },
  write: false,
});
const script = bundle.outputFiles[0].text;
const style = await readFile(new URL('.generated/styles.css', root), 'utf8');
await mkdir(new URL('.generated/', root), { recursive: true });
const temporary = new URL(`.generated/web-${process.pid}.tmp`, root);
await writeFile(
  temporary,
  `// Generated by scripts/build-web.ts; edit web/ instead.\nexport const loginScript = ${JSON.stringify(script)};\nexport const stylesheet = ${JSON.stringify(style)};\n`,
);
// Dev watchers can read while rebuilding; publish a complete module atomically.
await rename(temporary, new URL('.generated/web.ts', root));
